### ISSUE TITLE
Support for Statistics Graph

### ISSUE THREAD

**Issue by archit3kt** [ualex73/monitor_docker#101]
Hi,

thanks for this great integration ! I'm glad to be able to monitor my containers on my HA :)

I'd love to put some CPU and memory stats in a Statistics Graph card but the entities are not listed. Apparently devs need to update something for the entities to be picked up by this card, here is the link :

https://www.home-assistant.io/more-info/statistics/

Could you please make the modification to allow us to use the statistics graph card ?

**Comment by luzik** [comment]
For long term statistics like disk usage, memory usage it would be awesome feature. Now showing chart for week of few containers is quite a pain because huge amount of data. Month is unusable. Statistics is a way to go, and it seams quite easy to get. I believe that entity have to define new state_class attribute and thats it. :)
