### ISSUE TITLE
Feature Request: MAC/IP address

### ISSUE THREAD

**Issue by LastElf** [ualex73/monitor_docker#121]
Be cool if we could monitor for MAC and IP addresses as attributes, I have an issue where I occasionally get MAC duplicates and it would be nice if I could trigger alerts when that happens.

**Comment by RoboMagus** [comment]
I'm playing around in the code-base a bit and it seems to be a pretty straightforward addition, so I'd be happy to open up a PR for this. 
However I don't really see any usecase in exposing this data.

The issue you mention seems to be quite specific and something that should be solved (prevented) by configuration rather than by notifying and manual intervention.

**Comment by ualex73** [comment]
I am also thinking about the use-case for this one? MAC address is not really useful for docker itself.

**Comment by ualex73** [comment]
If you got a PR, please raise ... I will close this ticket for now.
