### ISSUE TITLE
Uptime sensor issue // Feature Request

### ISSUE THREAD

**Issue by apedance** [ualex73/monitor_docker#2]
Hey,

again.

The uptime sensor seems to have issues.
![image](https://user-images.githubusercontent.com/4264240/84602093-46354100-ae85-11ea-8893-a75069aa1ae8.png)

How can I help and provide logs to you?

///////////////

Feature Request

Can you pass on a basic naming scheme for the sensors?

Like 

ovpn_fam CPU Usage
containername Memory Used
containername Memory %
...

Glances does this well.

![image](https://user-images.githubusercontent.com/4264240/84602398-fc495c80-ae7e-11ea-9867-d053bf9a4ad2.png)

Cheers o/

**Comment by ualex73** [comment]
For the uptime I pushed a fix to github. For the sensor name best to remove ‘sensorname’ from your configuration. I made in the fix also the name of a sensor ‘<container> <sensor>’. So now it a bit more generic and does not follow my personal setup 🤪
Thanks for reporting the bug and if you find more, please let me know. Same applies for feature requests, then I will check what I can do.

**Comment by apedance** [comment]
#fixed
Great work.

Will mess around with it further.

Cheers o/

**Comment by ualex73** [comment]
Thanks for the confirmation it works good.

BTW: the total memory used by docker containers in glances and monitor_docker will differ, because glances seem to count also cache memory (this is released when needed) and i only count real memory (on my system Glances show 17GB and my memory shows 7GB ;-)).
